# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "acs_new_bundle"
#   createdAt: 2022-07-29T19:44:59.7761619Z
#   expiresAt: 2023-07-29T19:45:00Z
#   id:        606105ad-428c-406b-899b-df7386a8a590
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-07-29T19:44:59.7761619Z"
    init-bundle.stackrox.io/expires-at: "2023-07-29T19:45:00Z"
    init-bundle.stackrox.io/id: 606105ad-428c-406b-899b-df7386a8a590
    init-bundle.stackrox.io/name: acs_new_bundle
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUDOIQdEBiSYXCKgPjrvMDIxaKV18wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MB4XDTIyMDcyNzIwMjcwMFoXDTI3MDcy
    NjIwMjcwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/BcIAZWbTxTYXtxhlBjb4xVpsmQtjPhNECdlbkONOv763jcZ
    fU6dwPT59y2X1rmcjH3nguolW1bDKZpxQKoaYaNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMEbcZnBCOfzLPiEZhfoqz+4vakL
    MAoGCCqGSM49BAMCA0gAMEUCICcVrM6wwJAB/FSRZMwDgWbND4eaaRc+lm5XqL8t
    b7b2AiEA/u2VFJGaZ1cQkxbyyOUa+MgHrrNzmeYbm/LKvnl2VhA=
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICoTCCAkigAwIBAgIJAIcj630s/K3sMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTNzYxNjAw
    OTk3MDgzOTAzNDAwOTAeFw0yMjA3MjkxODQ1MDBaFw0yMzA3MjkxOTQ1MDBaMIGr
    MS0wKwYDVQQKEyQ2MDYxMDVhZC00MjhjLTQwNmItODk5Yi1kZjczODZhOGE1OTAx
    GjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNFMUAwPgYDVQQDDDdDT0xMRUNUT1Jf
    U0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMRww
    GgYDVQQFExM5NzM3ODg1NzQyMTYzMzQwNzgwMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAE9HDS5P4tevhTqYyYqQ3kAKYzIt3pFx/GynKAKvrI6lU/jDU8MP1yMhzm
    dCDvKJauulIOgSLV1u0Uly5xBEk8tKOBtzCBtDAOBgNVHQ8BAf8EBAMCBaAwHQYD
    VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
    BBYEFM5P3/fnVb9CWFEnVt8j4K1l8HDcMB8GA1UdIwQYMBaAFMEbcZnBCOfzLPiE
    Zhfoqz+4vakLMDUGA1UdEQQuMCyCEmNvbGxlY3Rvci5zdGFja3JveIIWY29sbGVj
    dG9yLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNHADBEAiBCRzFLChBdl9U1i1Ho
    8E8Cd5U9JYSuQxTK6GbVe62SdgIgJwK2DHR/U3V86lk0IWD/8tk5kZzwRCjCHhCh
    xLgyZJY=
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIEZu7NLQ35egXL6cX04DH3eqndzuj/EpqbLVnHldMEmKoAoGCCqGSM49
    AwEHoUQDQgAE9HDS5P4tevhTqYyYqQ3kAKYzIt3pFx/GynKAKvrI6lU/jDU8MP1y
    MhzmdCDvKJauulIOgSLV1u0Uly5xBEk8tA==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-07-29T19:44:59.7761619Z"
    init-bundle.stackrox.io/expires-at: "2023-07-29T19:45:00Z"
    init-bundle.stackrox.io/id: 606105ad-428c-406b-899b-df7386a8a590
    init-bundle.stackrox.io/name: acs_new_bundle
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUDOIQdEBiSYXCKgPjrvMDIxaKV18wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MB4XDTIyMDcyNzIwMjcwMFoXDTI3MDcy
    NjIwMjcwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/BcIAZWbTxTYXtxhlBjb4xVpsmQtjPhNECdlbkONOv763jcZ
    fU6dwPT59y2X1rmcjH3nguolW1bDKZpxQKoaYaNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMEbcZnBCOfzLPiEZhfoqz+4vakL
    MAoGCCqGSM49BAMCA0gAMEUCICcVrM6wwJAB/FSRZMwDgWbND4eaaRc+lm5XqL8t
    b7b2AiEA/u2VFJGaZ1cQkxbyyOUa+MgHrrNzmeYbm/LKvnl2VhA=
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICsjCCAligAwIBAgIIZ8rDsLcTNQQwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM3NjE2MDA5
    OTcwODM5MDM0MDA5MB4XDTIyMDcyOTE4NDUwMFoXDTIzMDcyOTE5NDUwMFowgaUx
    LTArBgNVBAoTJDYwNjEwNWFkLTQyOGMtNDA2Yi04OTliLWRmNzM4NmE4YTU5MDEX
    MBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNF
    OiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUT
    Ezc0NzkwMDUyOTQ5NTUyNzk2MjAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASe
    7TkykB0SMReszrVBzMCsZYxI6/C+fkG2Fy88364+YbVhxzNGLbL4ivw8TAuiZste
    mfCZ4zqEBL81aq7sPdBjo4HOMIHLMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU94RJ
    WRMU8fF1zUi8HTzzxFAG7S0wHwYDVR0jBBgwFoAUwRtxmcEI5/Ms+IRmF+irP7i9
    qQswTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNrcm94ghNzZW5zb3Iuc3RhY2tyb3gu
    c3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSAAw
    RQIgUB+yoc+4XOn20TTjLi5dtPeMnJ0Cp3tbPaUay6EgE+gCIQC/c+0xXdiQcO+o
    yjCuQ2oepIcyf8Pkyxsj/D0js3uwJw==
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIA4GkL6UYTJpQP5slEbMBx6hMK3KYNwDVBiGJVdEAFvNoAoGCCqGSM49
    AwEHoUQDQgAEnu05MpAdEjEXrM61QczArGWMSOvwvn5BthcvPN+uPmG1YcczRi2y
    +Ir8PEwLombLXpnwmeM6hAS/NWqu7D3QYw==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-07-29T19:44:59.7761619Z"
    init-bundle.stackrox.io/expires-at: "2023-07-29T19:45:00Z"
    init-bundle.stackrox.io/id: 606105ad-428c-406b-899b-df7386a8a590
    init-bundle.stackrox.io/name: acs_new_bundle
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwTCCAmegAwIBAgIIeSPjEG10msIwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM3NjE2MDA5
    OTcwODM5MDM0MDA5MB4XDTIyMDcyOTE4NDUwMFoXDTIzMDcyOTE5NDUwMFowgbsx
    LTArBgNVBAoTJDYwNjEwNWFkLTQyOGMtNDA2Yi04OTliLWRmNzM4NmE4YTU5MDEi
    MCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTFIMEYGA1UEAww/QURN
    SVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
    MDAwMDAwMDAwMDAwMRwwGgYDVQQFExM4NzI5MDcwMTYyNDY5NDkzNDQyMFkwEwYH
    KoZIzj0CAQYIKoZIzj0DAQcDQgAEb0P1lLqfWmYmd6URLT+8D6R6450Kurkr3oVH
    w4CoxnBzZu7s6j9CeqdP2joUXElSPdkdZ/0aZRz/E94PGIU+3aOBxzCBxDAOBgNV
    HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
    EwEB/wQCMAAwHQYDVR0OBBYEFM5IGTTnVnJr+b9SHwo5DEssucvrMB8GA1UdIwQY
    MBaAFMEbcZnBCOfzLPiEZhfoqz+4vakLMEUGA1UdEQQ+MDyCGmFkbWlzc2lvbi1j
    b250cm9sLnN0YWNrcm94gh5hZG1pc3Npb24tY29udHJvbC5zdGFja3JveC5zdmMw
    CgYIKoZIzj0EAwIDSAAwRQIgKz1scinLsdzmOCwvApJl1HCW41DJagWbDgtr3Xtn
    7GUCIQCgtLHao70jzfaKDwOLi8/efOkWhSHdvqIClONcWUQ+Vg==
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEICf2gwciijWFxKOuRHNfBvRECAUwKomUqO0b+pr4wP0VoAoGCCqGSM49
    AwEHoUQDQgAEb0P1lLqfWmYmd6URLT+8D6R6450Kurkr3oVHw4CoxnBzZu7s6j9C
    eqdP2joUXElSPdkdZ/0aZRz/E94PGIU+3Q==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUDOIQdEBiSYXCKgPjrvMDIxaKV18wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MB4XDTIyMDcyNzIwMjcwMFoXDTI3MDcy
    NjIwMjcwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM3NjE2MDA5OTcwODM5MDM0MDA5MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAE/BcIAZWbTxTYXtxhlBjb4xVpsmQtjPhNECdlbkONOv763jcZ
    fU6dwPT59y2X1rmcjH3nguolW1bDKZpxQKoaYaNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMEbcZnBCOfzLPiEZhfoqz+4vakL
    MAoGCCqGSM49BAMCA0gAMEUCICcVrM6wwJAB/FSRZMwDgWbND4eaaRc+lm5XqL8t
    b7b2AiEA/u2VFJGaZ1cQkxbyyOUa+MgHrrNzmeYbm/LKvnl2VhA=
    -----END CERTIFICATE-----
